Upgrade gem for Rails 7 compatibility
mainio/ratonvirus pull request #17
Opened 2022-01-09 13:58 UTC by geetfun

This PR upgrades the gem to work with Rails 7. 

Notes:
- The existing code base works without any modifications
- Some regex were modified in the specs to accommodate for `Tempfile` directories other than /tmp. Not sure if it is due to Ruby 2.7 (requirement for Rails 7)
- Bumped semver

2022-01-13 23:49 UTC, Laykou commented
@ahukkanen Could this be merged please and released under new version?

2022-02-07 13:47 UTC, ahukkanen requested changes
I don't see the necessity for the `tmp` related changes which are also causing rubocop violations.

Can you also run rubocop and fix the violations that it provides.

Please also change the `config.load_defaults` to match the targeted Rails version at the dummy app.

2022-02-07 13:47 UTC, ahukkanen commented on spec/lib/ratonvirus/storage/active_storage_spec.rb
> +            %r{/*?\/Ratonvirus[0-9]+-[0-9]+-[0-9a-z]+\.pdf}
Can you revert this back to `/tmp`?

2022-02-07 13:47 UTC, ahukkanen commented on spec/lib/ratonvirus/storage/active_storage_spec.rb
> +            %r{/*?\/Ratonvirus[0-9]+-[0-9]+-[0-9a-z]+\.pdf}
Can you revert this back to `/tmp`?

2022-02-07 13:47 UTC, ahukkanen commented on spec/lib/ratonvirus/storage/active_storage_spec.rb
> +            %r{/*?\/RatonTest[0-9]+-[0-9]+-[0-9a-z]+\.txt}
Can you revert this back to `/tmp`?

2022-02-07 13:47 UTC, ahukkanen commented on spec/lib/ratonvirus/storage/carrierwave_spec.rb
> +          %r{/*?\/Ratonvirus[0-9]+-[0-9]+-[0-9a-z]+\.pdf}
Can you revert this back to `/tmp`?

2022-02-07 13:47 UTC, ahukkanen commented on spec/lib/ratonvirus/storage/carrierwave_spec.rb
> +            %r{/*?\/Ratonvirus[0-9]+-[0-9]+-[0-9a-z]+\.pdf}
Can you revert this back to `/tmp`?

2022-02-07 13:51 UTC, ahukkanen commented
It seems also that Rubocop is giving a `parser` related warning due to the mismatch of Ruby version.

Please also run `bundle update parser` and commit the updated `Gemfile.lock`. This fixes the warning.

2022-02-08 15:20 UTC, geetfun commented
> It seems also that Rubocop is giving a `parser` related warning due to the mismatch of Ruby version.
> 
> Please also run `bundle update parser` and commit the updated `Gemfile.lock`. This fixes the warning.

Sounds good. I'll make those changes and update the PR. Thanks

2022-02-17 08:10 UTC, ahukkanen requested changes
Thank you @geetfun !

Few more things
> Please also change the config.load_defaults to match the targeted Rails version at the dummy app.
https://github.com/mainio/ratonvirus/blob/b4eb864f14b250d0926ff84476e2ed48c39f7ef9/spec/rails_dummy_app/config/application.rb#L11

Also left one comment regarding the CHANGELOG.

2022-02-17 08:10 UTC, ahukkanen commented on CHANGELOG.md
> +- Some test regular expressions
Can you take this CHANGELOG note off since it's not accurate anymore?

2022-02-28 17:33 UTC, geetfun commented
@ahukkanen Changes updated. Thanks!

2022-03-14 15:58 UTC, ahukkanen approved these changes
Thanks a lot, LGTM!

2022-03-14 17:00 UTC, merged